import numpy as np
import os
import shutil
import struct
import tkinter as tk
from tkinter import filedialog, messagebox

def main():
    print('This script "fixes" a .up1 file generated by EDAX TEAM to ensure compatibility with EmSphInx.')
    print("Original version by Tijmen Vermeij (2022), updated by Alex Wang (2025)")
    print("\nIt is recommended to keep the .up1 file with the .osc file.\n")
    
    # GUI file picker
    root = tk.Tk()
    root.withdraw()
    messagebox.showinfo("Step 1", "Select the .up1 file created by EDAX TEAM")
    file_path = filedialog.askopenfilename(
        title='Select the .up1 file created by EDAX TEAM',
        filetypes=[('UP1 files', '*.up1')]
    )

    if not file_path:
        print("User canceled file selection.")
        return

    print("This may take a couple minutes. Please be patient...\n")

    # Create backup
    fname_orig = file_path.replace('.up1', '_old.up1')
    shutil.move(file_path, fname_orig)
    fname_new = file_path

    with open(fname_orig, 'rb') as f_orig:
        header_bytes = f_orig.read(16)
        header = struct.unpack('<4I', header_bytes)
        pattern_size = (header[1], header[2])
        byte_start = header[3]

        f_orig.seek(0, os.SEEK_END)
        file_size = f_orig.tell()
        f_orig.seek(byte_start)

        no_pix_per_pattern = pattern_size[0] * pattern_size[1]
        no_patterns = (file_size - byte_start) // no_pix_per_pattern
        max_pat_read = 500

        with open(fname_new, 'wb') as f_new:
            new_header = struct.pack('<4I', 1, pattern_size[0], pattern_size[1], 16)
            f_new.write(new_header)
            f_new.seek(16)

            for i in range(0, no_patterns, max_pat_read):
                chunk_size = min(max_pat_read, no_patterns - i)
                num_bytes = chunk_size * no_pix_per_pattern
                data = np.frombuffer(f_orig.read(num_bytes), dtype=np.uint8)
                f_new.write(data.tobytes())

    print("\n✅ Operation complete!")
    print("The old file has been renamed with '_old.up1'. You can now convert the new file to .h5 as usual.")
    print("Please delete both .up1 files once you have ensured the .h5 file works.")
    input("\nPress Enter to exit...")

if __name__ == '__main__':
    main()
